package com.admitx.view;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

public class UserGuidePage {

    public static Scene getScene() {

        // =====================================================
        // PAGE TITLE
        // =====================================================

        Label title = new Label("User Guide & Important Terms");

        title.setStyle(
                "-fx-font-size: 30px;" +
                "-fx-font-weight: bold;" +
                "-fx-text-fill: #FBFBFB;"
        );

        Label subtitle = new Label(
                "Please read the following information carefully before continuing."
        );

        subtitle.setStyle(
                "-fx-font-size: 14px;" +
                "-fx-text-fill: #D4CBB6;"
        );


        // =====================================================
        // IMPORTANT NOTICE
        // =====================================================

        Label noticeTitle = new Label(
                "⚠  IMPORTANT NOTICE"
        );

        noticeTitle.setStyle(
                "-fx-font-size: 17px;" +
                "-fx-font-weight: bold;" +
                "-fx-text-fill: #C6E92F;"
        );

        Label noticeText = new Label(
                "AdmitX is an educational CAP counselling simulation system.\n\n" +

                "An allotment generated by AdmitX is a simulated result and must NOT " +
                "be interpreted as your actual CET/CAP allotment."
        );

        noticeText.setWrapText(true);

        noticeText.setStyle(
                "-fx-font-size: 14px;" +
                "-fx-text-fill: #FBFBFB;"
        );

        VBox noticeBox = new VBox(
                10,
                noticeTitle,
                noticeText
        );

        noticeBox.setPadding(
                new Insets(20)
        );

        noticeBox.setStyle(
                "-fx-background-color: #161613;" +
                "-fx-border-color: #C6E92F;" +
                "-fx-border-width: 1;" +
                "-fx-background-radius: 12;" +
                "-fx-border-radius: 12;"
        );


        // =====================================================
        // TERMS
        // =====================================================

        VBox termsBox = new VBox(18);

        termsBox.setPadding(
                new Insets(20)
        );

        termsBox.setStyle(
                "-fx-background-color: #161613;" +
                "-fx-border-color: #3F340D;" +
                "-fx-border-width: 1;" +
                "-fx-background-radius: 12;" +
                "-fx-border-radius: 12;"
        );


        // =====================================================
        // 01 - ABOUT ADMITX
        // =====================================================

        termsBox.getChildren().add(
                createSection(
                        "01",
                        "ABOUT ADMITX",
                        "AdmitX is designed to simulate the college counselling process, " +
                        "including merit-based ranking, college preferences, seat availability, " +
                        "and simulated seat allotment.\n\n" +

                        "The purpose of this application is to help students understand " +
                        "how a counselling and seat-allotment system may work."
                )
        );


        // =====================================================
        // 02 - SIMULATION RESULTS
        // =====================================================

        termsBox.getChildren().add(
                createSection(
                        "02",
                        "SIMULATION RESULTS",
                        "Any college, branch, seat, rank, or allotment displayed by AdmitX " +
                        "is generated by the application's simulation system.\n\n" +

                        "These results:\n" +
                        "• Do not represent official CET results.\n" +
                        "• Do not represent official CAP allotments.\n" +
                        "• Do not guarantee admission to any college.\n" +
                        "• May differ from actual counselling results.\n" +
                        "• Should not be used as an official admission decision.\n\n" +

                        "A simulated allotment in AdmitX does NOT mean that the same " +
                        "college or branch will be allotted to you in an actual CAP round."
                )
        );


        // =====================================================
        // 03 - NO ADMISSION GUARANTEE
        // =====================================================

        termsBox.getChildren().add(
                createSection(
                        "03",
                        "NO ADMISSION GUARANTEE",
                        "AdmitX does not guarantee admission to any particular college, " +
                        "branch, course, or institute.\n\n" +

                        "Actual admission depends on factors such as:\n" +
                        "• Official merit rank\n" +
                        "• Candidate eligibility\n" +
                        "• Seat availability\n" +
                        "• College and branch preferences\n" +
                        "• CAP round rules\n" +
                        "• Cut-offs\n" +
                        "• Government/CET Cell regulations\n" +
                        "• Other official admission criteria.\n\n" +

                        "The actual admission outcome may therefore be different " +
                        "from the result generated by AdmitX."
                )
        );


        // =====================================================
        // 04 - STUDENT RESPONSIBILITY
        // =====================================================

        termsBox.getChildren().add(
                createSection(
                        "04",
                        "STUDENT RESPONSIBILITY",
                        "Students are responsible for entering accurate information " +
                        "into the application.\n\n" +

                        "This may include:\n" +
                        "• CET percentile\n" +
                        "• Academic information\n" +
                        "• College preferences\n" +
                        "• Branch preferences\n" +
                        "• Other required details.\n\n" +

                        "Incorrect or incomplete information may result in an " +
                        "inaccurate simulated outcome."
                )
        );


        // =====================================================
        // 05 - COLLEGE & SEAT INFORMATION
        // =====================================================

        termsBox.getChildren().add(
                createSection(
                        "05",
                        "COLLEGE & SEAT INFORMATION",
                        "College, branch, seat, and availability information displayed " +
                        "in AdmitX may be sample, dummy, or simulated data created " +
                        "for demonstration purposes.\n\n" +

                        "Students should not assume that the displayed seat availability " +
                        "represents the current availability in actual CAP rounds."
                )
        );


        // =====================================================
        // 06 - OFFICIAL INFORMATION
        // =====================================================

        termsBox.getChildren().add(
                createSection(
                        "06",
                        "OFFICIAL INFORMATION",
                        "For actual admission decisions, students must always refer to " +
                        "the official CET Cell notifications, CAP schedules, merit lists, " +
                        "seat matrices, cut-offs, and allotment results.\n\n" +

                        "AdmitX should be used only as a guidance and educational " +
                        "simulation tool."
                )
        );


        // =====================================================
        // 07 - UNDERSTANDING THE CAP SIMULATION
        // =====================================================

        termsBox.getChildren().add(
                createSection(
                        "07",
                        "UNDERSTANDING THE CAP SIMULATION",
                        "The AdmitX simulation may include multiple counselling rounds.\n\n" +

                        "FREEZE\n" +
                        "Accept the simulated allotment and stop participating in further " +
                        "simulated rounds.\n\n" +

                        "FLOAT\n" +
                        "Continue participating in the next simulated round while retaining " +
                        "the current simulated allotment according to the application's rules.\n\n" +

                        "NEXT ROUND\n" +
                        "Continue the simulation to see how the allotment may change based " +
                        "on preferences and simulated seat availability.\n\n" +

                        "These options are part of the AdmitX simulation and should not " +
                        "be treated as an official representation of the current CET/CAP process."
                )
        );


        // =====================================================
        // 08 - AI RECOMMENDATIONS
        // =====================================================

        termsBox.getChildren().add(
                createSection(
                        "08",
                        "AI RECOMMENDATIONS",
                        "AdmitX may use AI-based recommendations to suggest colleges or " +
                        "branches based on the information provided by the student.\n\n" +

                        "AI recommendations are intended for guidance and educational " +
                        "purposes only.\n\n" +

                        "Students should independently verify college information, " +
                        "eligibility requirements, cut-offs, fees, and admission rules " +
                        "through official sources before making actual admission decisions."
                )
        );


        // =====================================================
        // FINAL DISCLAIMER
        // =====================================================

        Label finalTitle = new Label(
                "⚠  FINAL DISCLAIMER"
        );

        finalTitle.setStyle(
                "-fx-font-size: 17px;" +
                "-fx-font-weight: bold;" +
                "-fx-text-fill: #C6E92F;"
        );

        Label finalText = new Label(
                "AdmitX is a simulation — not the official CET/CAP admission system.\n\n" +

                "An allotment generated by AdmitX is a simulated result and must NOT " +
                "be interpreted as your actual CET/CAP allotment.\n\n" +

                "Always verify your actual admission status through the appropriate " +
                "official admission authority."
        );

        finalText.setWrapText(true);

        finalText.setStyle(
                "-fx-font-size: 14px;" +
                "-fx-text-fill: #FBFBFB;"
        );

        VBox finalBox = new VBox(
                10,
                finalTitle,
                finalText
        );

        finalBox.setPadding(
                new Insets(20)
        );

        finalBox.setStyle(
                "-fx-background-color: #10110D;" +
                "-fx-border-color: #8AA30B;" +
                "-fx-border-width: 1;" +
                "-fx-background-radius: 12;" +
                "-fx-border-radius: 12;"
        );

        termsBox.getChildren().add(finalBox);


        // =====================================================
        // AGREEMENT CHECKBOX
        // THIS IS NOW INSIDE THE SCROLL
        // =====================================================

        CheckBox agreeCheckBox = new CheckBox(
                "I have read and understood the User Guide, Terms, and Simulation Disclaimer."
        );

        agreeCheckBox.setWrapText(true);

        agreeCheckBox.setStyle(
                "-fx-text-fill: #FBFBFB;" +
                "-fx-font-size: 13px;"
        );


        // =====================================================
        // CONTINUE BUTTON
        // =====================================================

        Button continueButton = new Button(
                "AGREE & CONTINUE  →"
        );

        continueButton.setPrefWidth(260);
        continueButton.setPrefHeight(45);

        continueButton.setDisable(true);

        continueButton.setStyle(
                "-fx-background-color: #3A3B38;" +
                "-fx-text-fill: #77786F;" +
                "-fx-font-size: 13px;" +
                "-fx-font-weight: bold;" +
                "-fx-background-radius: 8;"
        );


        // =====================================================
        // ENABLE BUTTON AFTER AGREEMENT
        // =====================================================

        agreeCheckBox.selectedProperty().addListener(
                (observable, oldValue, newValue) -> {

                    if (newValue) {

                        continueButton.setDisable(false);

                        continueButton.setStyle(
                                "-fx-background-color: #C6E92F;" +
                                "-fx-text-fill: #040505;" +
                                "-fx-font-size: 13px;" +
                                "-fx-font-weight: bold;" +
                                "-fx-background-radius: 8;"
                        );

                    } else {

                        continueButton.setDisable(true);

                        continueButton.setStyle(
                                "-fx-background-color: #3A3B38;" +
                                "-fx-text-fill: #77786F;" +
                                "-fx-font-size: 13px;" +
                                "-fx-font-weight: bold;" +
                                "-fx-background-radius: 8;"
                        );
                    }
                }
        );


        // =====================================================
        // CONTINUE ACTION
        // =====================================================

        continueButton.setOnAction(e ->
                Navigation.goTo(
                        StudentLoginPage.getScene()
                )
        );


        // =====================================================
        // AGREEMENT BOX
        // ADDED AT THE VERY END OF SCROLL
        // =====================================================

        VBox agreementBox = new VBox(
                15,
                agreeCheckBox,
                continueButton
        );

        agreementBox.setAlignment(
                Pos.CENTER
        );

        agreementBox.setPadding(
                new Insets(25)
        );

        agreementBox.setStyle(
                "-fx-background-color: #10110D;" +
                "-fx-border-color: #C6E92F;" +
                "-fx-border-width: 1;" +
                "-fx-background-radius: 12;" +
                "-fx-border-radius: 12;"
        );

        termsBox.getChildren().add(
                agreementBox
        );


        // =====================================================
        // SCROLL PANE
        // =====================================================

        ScrollPane scrollPane = new ScrollPane(
                termsBox
        );

        scrollPane.setFitToWidth(true);

        scrollPane.setHbarPolicy(
                ScrollPane.ScrollBarPolicy.NEVER
        );

        scrollPane.setStyle(
                "-fx-background-color: transparent;"
        );


        // =====================================================
        // FOOTER
        // =====================================================

        Label footer = new Label(
                "© 2026 ADMITX • Smarter Admissions"
        );

        footer.setStyle(
                "-fx-font-size: 11px;" +
                "-fx-text-fill: #77786F;"
        );

        VBox footerBox = new VBox(
                footer
        );

        footerBox.setAlignment(
                Pos.CENTER
        );

        footerBox.setPadding(
                new Insets(10, 20, 15, 20)
        );


        // =====================================================
        // MAIN CONTENT
        // =====================================================

        VBox mainContent = new VBox(
                20,
                title,
                subtitle,
                noticeBox,
                scrollPane
        );

        mainContent.setAlignment(
                Pos.TOP_CENTER
        );

        mainContent.setPadding(
                new Insets(30, 60, 10, 60)
        );

        VBox.setVgrow(
                scrollPane,
                javafx.scene.layout.Priority.ALWAYS
        );


        // =====================================================
        // HEADER
        // =====================================================

        Label logo = new Label(
                "ADMITX"
        );

        logo.setStyle(
                "-fx-font-size: 25px;" +
                "-fx-font-weight: bold;" +
                "-fx-text-fill: #C6E92F;"
        );


        Label headerText = new Label(
                "SMARTER ADMISSIONS"
        );

        headerText.setStyle(
                "-fx-font-size: 9px;" +
                "-fx-font-weight: bold;" +
                "-fx-text-fill: #D4CBB6;"
        );


        VBox logoBox = new VBox(
                2,
                logo,
                headerText
        );


        BorderPane header = new BorderPane();

        header.setLeft(
                logoBox
        );

        header.setPadding(
                new Insets(18, 35, 18, 35)
        );

        header.setStyle(
                "-fx-background-color: #040505;" +
                "-fx-border-color: transparent transparent #3F340D transparent;" +
                "-fx-border-width: 0 0 1 0;"
        );


        // =====================================================
        // ROOT
        // =====================================================

        BorderPane root = new BorderPane();

        root.setTop(header);

        root.setCenter(mainContent);

        root.setBottom(footerBox);

        root.setStyle(
                "-fx-background-color: #040505;"
        );


        // =====================================================
        // SCENE
        // =====================================================

        return new Scene(
                root,
                1200,
                800
        );
    }


    // =========================================================
    // CREATE TERM SECTION
    // =========================================================

    private static VBox createSection(
            String number,
            String heading,
            String content
    ) {

        Label numberLabel = new Label(
                number
        );

        numberLabel.setStyle(
                "-fx-font-size: 13px;" +
                "-fx-font-weight: bold;" +
                "-fx-text-fill: #C6E92F;"
        );


        Label headingLabel = new Label(
                heading
        );

        headingLabel.setStyle(
                "-fx-font-size: 16px;" +
                "-fx-font-weight: bold;" +
                "-fx-text-fill: #FBFBFB;"
        );


        HBox headingBox = new HBox(
                10,
                numberLabel,
                headingLabel
        );

        headingBox.setAlignment(
                Pos.CENTER_LEFT
        );


        Label contentLabel = new Label(
                content
        );

        contentLabel.setWrapText(true);

        contentLabel.setStyle(
                "-fx-font-size: 13px;" +
                "-fx-text-fill: #D4CBB6;" +
                "-fx-line-spacing: 3px;"
        );


        VBox section = new VBox(
                10,
                headingBox,
                contentLabel
        );

        section.setPadding(
                new Insets(18)
        );

        section.setStyle(
                "-fx-background-color: #2B2C2B;" +
                "-fx-border-color: #3F3F38;" +
                "-fx-border-width: 1;" +
                "-fx-background-radius: 10;" +
                "-fx-border-radius: 10;"
        );


        return section;
    }
}